/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";

export enum FrameRate {
  _2398 = <any>"23.98",
  _2400 = <any>"24.00",
  _24 = <any>"24",
  _2500 = <any>"25.00",
  _25 = <any>"25",
  _2997 = <any>"29.97",
  _3000 = <any>"30.00",
  _30 = <any>"30",
  _4795 = <any>"47.95",
  _4800 = <any>"48.00",
  _48 = <any>"48",
  _5000 = <any>"50.00",
  _50 = <any>"50",
  _5994 = <any>"59.94",
  _6000 = <any>"60.00",
  _60 = <any>"60",
  _11988 = <any>"119.88",
  _12000 = <any>"120.00",
  _120 = <any>"120",
}
