/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";

export class Gain {
  "red"?: number = 0.0;
  "green"?: number = 0.0;
  "blue"?: number = 0.0;
  "luma"?: number = 0.0;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "red",
      baseName: "red",
      type: "number",
    },
    {
      name: "green",
      baseName: "green",
      type: "number",
    },
    {
      name: "blue",
      baseName: "blue",
      type: "number",
    },
    {
      name: "luma",
      baseName: "luma",
      type: "number",
    },
  ];

  static getAttributeTypeMap() {
    return Gain.attributeTypeMap;
  }
}
