/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";
import { FrameRate } from "./frameRate";

export class GetVideoFormat {
  /**
   * Video format serialised as a string
   */
  "name"?: string;
  "frameRate"?: FrameRate;
  /**
   * Height dimension of video format
   */
  "height"?: number;
  /**
   * Width dimension of video format
   */
  "width"?: number;
  /**
   * Is the display format interlaced?
   */
  "interlaced"?: boolean;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "name",
      baseName: "name",
      type: "string",
    },
    {
      name: "frameRate",
      baseName: "frameRate",
      type: "FrameRate",
    },
    {
      name: "height",
      baseName: "height",
      type: "number",
    },
    {
      name: "width",
      baseName: "width",
      type: "number",
    },
    {
      name: "interlaced",
      baseName: "interlaced",
      type: "boolean",
    },
  ];

  static getAttributeTypeMap() {
    return GetVideoFormat.attributeTypeMap;
  }
}

export namespace GetVideoFormat {}
