/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";

export class Input {
  "input"?: Input.InputEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "input",
      baseName: "input",
      type: "Input.InputEnum",
    },
  ];

  static getAttributeTypeMap() {
    return Input.attributeTypeMap;
  }
}

export namespace Input {
  export enum InputEnum {
    None = <any>"None",
    CameraLeft = <any>"Camera - Left",
    CameraRight = <any>"Camera - Right",
    CameraMono = <any>"Camera - Mono",
    Xlr1Mic = <any>"XLR1 - Mic",
    Xlr1Line = <any>"XLR1 - Line",
    Xlr2Mic = <any>"XLR2 - Mic",
    Xlr2Line = <any>"XLR2 - Line",
    _35mmLeftLine = <any>"3.5mm Left - Line",
    _35mmLeftMic = <any>"3.5mm Left - Mic",
    _35mmRightLine = <any>"3.5mm Right - Line",
    _35mmRightMic = <any>"3.5mm Right - Mic",
    _35mmMonoLine = <any>"3.5mm Mono - Line",
    _35mmMonoMic = <any>"3.5mm Mono - Mic",
  }
}
