/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";

export class LensZoomGet200Response {
  /**
   * Focal length in mm
   */
  "focalLength"?: number;
  /**
   * Normalised value
   */
  "normalised"?: number;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "focalLength",
      baseName: "focalLength",
      type: "number",
    },
    {
      name: "normalised",
      baseName: "normalised",
      type: "number",
    },
  ];

  static getAttributeTypeMap() {
    return LensZoomGet200Response.attributeTypeMap;
  }
}
