/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";

export class LensIrisPutRequest {
  /**
   * Aperture stop value
   */
  "apertureStop"?: number;
  /**
   * Normalised value
   */
  "normalised"?: number;
  /**
   * Aperture number
   */
  "apertureNumber"?: number;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "apertureStop",
      baseName: "apertureStop",
      type: "number",
    },
    {
      name: "normalised",
      baseName: "normalised",
      type: "number",
    },
    {
      name: "apertureNumber",
      baseName: "apertureNumber",
      type: "number",
    },
  ];

  static getAttributeTypeMap() {
    return LensIrisPutRequest.attributeTypeMap;
  }
}
