/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";

export class MediaDeviceInformation {
  /**
   * The current state of the media device.
   */
  "state"?: MediaDeviceInformation.StateEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "state",
      baseName: "state",
      type: "MediaDeviceInformation.StateEnum",
    },
  ];

  static getAttributeTypeMap() {
    return MediaDeviceInformation.attributeTypeMap;
  }
}

export namespace MediaDeviceInformation {
  export enum StateEnum {
    None = <any>"None",
    Scanning = <any>"Scanning",
    Mounted = <any>"Mounted",
    Uninitialised = <any>"Uninitialised",
    Formatting = <any>"Formatting",
    RaidComponent = <any>"RaidComponent",
  }
}
