/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";

export class MediaDevicesDeviceNameDoformatPutRequest {
  /**
   * The key used to format this device, it must be fetched with the GET request and then provided back with a PUT request
   */
  "key"?: string;
  /**
   * Filesystem to format to (supportedFilesystems returns list of supported fileSystems)
   */
  "filesystem"?: string;
  /**
   * Volume name to set for the disk after format
   */
  "volume"?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "key",
      baseName: "key",
      type: "string",
    },
    {
      name: "filesystem",
      baseName: "filesystem",
      type: "string",
    },
    {
      name: "volume",
      baseName: "volume",
      type: "string",
    },
  ];

  static getAttributeTypeMap() {
    return MediaDevicesDeviceNameDoformatPutRequest.attributeTypeMap;
  }
}
