/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";

export enum NdFilterDisplayMode {
  Stop = <any>"Stop",
  Number = <any>"Number",
  Fraction = <any>"Fraction",
}
