/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";

export class Playback {
  "type"?: Playback.TypeEnum;
  /**
   * When true playback loops from the end of the timeline to the beginning of the timeline
   */
  "loop"?: boolean;
  /**
   * When true playback loops from the end of the current clip to the beginning of the current clip
   */
  "singleClip"?: boolean;
  /**
   * Playback Speed, 1.0 for normal forward playback
   */
  "speed"?: number;
  /**
   * Playback position on the timeline in units of video frames
   */
  "position"?: number;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "type",
      baseName: "type",
      type: "Playback.TypeEnum",
    },
    {
      name: "loop",
      baseName: "loop",
      type: "boolean",
    },
    {
      name: "singleClip",
      baseName: "singleClip",
      type: "boolean",
    },
    {
      name: "speed",
      baseName: "speed",
      type: "number",
    },
    {
      name: "position",
      baseName: "position",
      type: "number",
    },
  ];

  static getAttributeTypeMap() {
    return Playback.attributeTypeMap;
  }
}

export namespace Playback {
  export enum TypeEnum {
    Play = <any>"Play",
    Jog = <any>"Jog",
    Shuttle = <any>"Shuttle",
    Var = <any>"Var",
  }
}
