/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";
import { Input } from "./input";

export class SupportedInputsSupportedInputsInner {
  "schema"?: Input;
  /**
   * Is the input available to be switched into from the current input for the selected channel
   */
  "available"?: boolean;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "schema",
      baseName: "schema",
      type: "Input",
    },
    {
      name: "available",
      baseName: "available",
      type: "boolean",
    },
  ];

  static getAttributeTypeMap() {
    return SupportedInputsSupportedInputsInner.attributeTypeMap;
  }
}
