/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";
import { CodecFormat } from "./codecFormat";

export class SupportedCodecFormats {
  "codecs"?: Array<CodecFormat>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "codecs",
      baseName: "codecs",
      type: "Array<CodecFormat>",
    },
  ];

  static getAttributeTypeMap() {
    return SupportedCodecFormats.attributeTypeMap;
  }
}
