/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";
import { FrameRate } from "./frameRate";
import { Resolution } from "./resolution";

export class SupportedFormat {
  "codecs"?: Array<string>;
  "frameRates"?: Array<FrameRate>;
  "maxOffSpeedFrameRate"?: number;
  "minOffSpeedFrameRate"?: number;
  "recordResolution"?: Resolution;
  "sensorResolution"?: Resolution;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "codecs",
      baseName: "codecs",
      type: "Array<string>",
    },
    {
      name: "frameRates",
      baseName: "frameRates",
      type: "Array<FrameRate>",
    },
    {
      name: "maxOffSpeedFrameRate",
      baseName: "maxOffSpeedFrameRate",
      type: "number",
    },
    {
      name: "minOffSpeedFrameRate",
      baseName: "minOffSpeedFrameRate",
      type: "number",
    },
    {
      name: "recordResolution",
      baseName: "recordResolution",
      type: "Resolution",
    },
    {
      name: "sensorResolution",
      baseName: "sensorResolution",
      type: "Resolution",
    },
  ];

  static getAttributeTypeMap() {
    return SupportedFormat.attributeTypeMap;
  }
}
