/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";
import { SupportedFormat } from "./supportedFormat";

export class SupportedFormats {
  "supportedFormats"?: Array<SupportedFormat>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "supportedFormats",
      baseName: "supportedFormats",
      type: "Array<SupportedFormat>",
    },
  ];

  static getAttributeTypeMap() {
    return SupportedFormats.attributeTypeMap;
  }
}
