/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";
import { CodecFormat } from "./codecFormat";
import { GetVideoFormat } from "./getVideoFormat";

/**
 * The properties will be populated only with the values that are supported/implemented by the device in use.
 */
export class SystemResponse {
  "codecFormat"?: CodecFormat;
  "videoFormat"?: GetVideoFormat;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "codecFormat",
      baseName: "codecFormat",
      type: "CodecFormat",
    },
    {
      name: "videoFormat",
      baseName: "videoFormat",
      type: "GetVideoFormat",
    },
  ];

  static getAttributeTypeMap() {
    return SystemResponse.attributeTypeMap;
  }
}
