/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";

export class TimecodeSource {
  "timecode"?: TimecodeSource.TimecodeEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "timecode",
      baseName: "timecode",
      type: "TimecodeSource.TimecodeEnum",
    },
  ];

  static getAttributeTypeMap() {
    return TimecodeSource.attributeTypeMap;
  }
}

export namespace TimecodeSource {
  export enum TimecodeEnum {
    Timecode = <any>"Timecode",
    Clip = <any>"Clip",
  }
}
