/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";

export class Timecode {
  /**
   * The time of day timecode in units of binary-coded decimal (BCD).
   */
  "timecode"?: number;
  /**
   * The position of the clip timecode in units of binary-coded decimal (BCD).
   */
  "clip"?: number;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "timecode",
      baseName: "timecode",
      type: "number",
    },
    {
      name: "clip",
      baseName: "clip",
      type: "number",
    },
  ];

  static getAttributeTypeMap() {
    return Timecode.attributeTypeMap;
  }
}
