/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";
import { NdFilterDisplayMode } from "./ndFilterDisplayMode";

export class VideoNdFilterDisplayModeGet200Response {
  "displayMode"?: NdFilterDisplayMode;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "displayMode",
      baseName: "displayMode",
      type: "NdFilterDisplayMode",
    },
  ];

  static getAttributeTypeMap() {
    return VideoNdFilterDisplayModeGet200Response.attributeTypeMap;
  }
}

export namespace VideoNdFilterDisplayModeGet200Response {}
