/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";
import { AutoExposureMode } from "./autoExposureMode";

export class VideoAutoExposureGet200Response {
  "mode"?: AutoExposureMode;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "mode",
      baseName: "mode",
      type: "AutoExposureMode",
    },
  ];

  static getAttributeTypeMap() {
    return VideoAutoExposureGet200Response.attributeTypeMap;
  }
}
