/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";
import { WorkingsetWorkingsetInner } from "./workingsetWorkingsetInner";

export class Workingset {
  /**
   * The fixed size of this device\'s working set
   */
  "size"?: number;
  "workingset"?: Array<WorkingsetWorkingsetInner>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "size",
      baseName: "size",
      type: "number",
    },
    {
      name: "workingset",
      baseName: "workingset",
      type: "Array<WorkingsetWorkingsetInner>",
    },
  ];

  static getAttributeTypeMap() {
    return Workingset.attributeTypeMap;
  }
}
