/**
 * merged spec
 * merged spec
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";

export class WorkingsetWorkingsetInner {
  /**
   * Index of this media in the working set
   */
  "index"?: number;
  /**
   * Is this current item the active disk
   */
  "activeDisk"?: boolean;
  /**
   * Volume name
   */
  "volume"?: string;
  /**
   * Internal device name of this media device
   */
  "deviceName"?: string;
  /**
   * Remaining record time on media device in seconds
   */
  "remainingRecordTime"?: number;
  /**
   * Total space on media device in bytes
   */
  "totalSpace"?: number;
  /**
   * Remaining space on media device in bytes
   */
  "remainingSpace"?: number;
  /**
   * Number of clips currently on the device
   */
  "clipCount"?: number;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "index",
      baseName: "index",
      type: "number",
    },
    {
      name: "activeDisk",
      baseName: "activeDisk",
      type: "boolean",
    },
    {
      name: "volume",
      baseName: "volume",
      type: "string",
    },
    {
      name: "deviceName",
      baseName: "deviceName",
      type: "string",
    },
    {
      name: "remainingRecordTime",
      baseName: "remainingRecordTime",
      type: "number",
    },
    {
      name: "totalSpace",
      baseName: "totalSpace",
      type: "number",
    },
    {
      name: "remainingSpace",
      baseName: "remainingSpace",
      type: "number",
    },
    {
      name: "clipCount",
      baseName: "clipCount",
      type: "number",
    },
  ];

  static getAttributeTypeMap() {
    return WorkingsetWorkingsetInner.attributeTypeMap;
  }
}
